### ISSUE TITLE
报错，无法运行

### ISSUE THREAD

**Issue by julyanghar** [Vaskka/GoogleCommonSpider#1]
Traceback (most recent call last):
  File "D:/Undergradute/project/Multi-view battleplane detection based on Machine learning/crawlers/google_Image/main.py", line 194, in <module>
    main()
  File "D:/Undergradute/project/Multi-view battleplane detection based on Machine learning/crawlers/google_Image/main.py", line 183, in main
    download(should_path)
  File "D:/Undergradute/project/Multi-view battleplane detection based on Machine learning/crawlers/google_Image/main.py", line 106, in download
    more_input = driver.find_element_by_id("smb")
  File "C:\Users\yyl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 360, in find_element_by_id
    return self.find_element(by=By.ID, value=id_)
  File "C:\Users\yyl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\yyl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\yyl\AppData\Local\Programs\Python\Python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"css selector","selector":"[id="smb"]"}
  (Session info: chrome=87.0.4280.88)

**Comment by xugaoxiang** [comment]
+1

**Comment by boyuzz** [comment]
+1

**Comment by qet119** [comment]
+1

**Comment by vinjancai** [comment]
+1
